### ISSUE TITLE
Site not loading images on search

### ISSUE THREAD

**Issue by DownToBius** [MegaMoo77/favorites-search#11]

**Comment by User3132425** [comment]
![Screenshot 2024-02-13 180548](https://github.com/MegaMoo77/favorites-search/assets/159971967/8c30535d-b745-4bf5-96e9-ecc4e2f85b18)
Similar issue here, glad to see it's not just me. The site is never able to request page 1 and won't load anything after that either. Adding tags or placing a custom request for a specific page does nothing.

**Comment by MegaMoo77** [comment]
Hey folks, it seems R34 has blocked the site, as well as the proxy it uses. For now, I've made a new version of both. It can be found at: https://cheerful-seahorse-01f6ad.netlify.app/favoritessearch.html
Also, the existing site should redirect.

If this happens again, I might need to put in some limitations to prevent abuse.

**Comment by DownToBius** [comment]
Sup MegaMoo, the sites gone back to non functional, or is more likey blocked.
