### ISSUE TITLE
Search only goes back 500 or so images

### ISSUE THREAD

**Issue by DownToBius** [MegaMoo77/favorites-search#3]
@MegaMoo77 
When searching, the tool only appears to look through my most recent 500ish images regardless of the tags. I've only noticed this recently when looking for older stuff. 

You've said before larger libraries take longer to search, which is understandable, but it just isn't loading all the images there are to load even after about 5 minutes of waiting

Edit: without applying any filters it appears to go back up to 2000, numbers vary by 200ish each time. I'll also note this wasnt the case a few months ago, as I could still reach my very first favs with a library of 6-7000

**Comment by MegaMoo77** [comment]
I was never able to reproduce this reliably, but I think it may be fixed now? I increased the sleep period after the server rejects a request, which slightly slows down the process, but seems to ensure it stops failing out. Let me know if you still see the problem.

**Comment by DownToBius** [comment]
> I was never able to reproduce this reliably, but I think it may be fixed now? I increased the sleep period after the server rejects a request, which slightly slows down the process, but seems to ensure it stops failing out. Let me know if you still see the problem.

**Comment by DownToBius** [comment]
Thats appears to have solved the issue. I thought the other day it might also be the search with any tags itself breaking somewhere and just stopping abruptly.

Maybe also the different capcha that was rescently reverted, but I doubt it.
